### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ja-som** [loserskater/suhide-GUI#2]
Hi, thanks for this app.
It works w/o any issue for me...

I have two requests...
1. search option in app list
2. reboot option, as I read on XDA we should reboot after add or remove app to blacklist, so it will be handy if we can do it right from your app

Thanks

**Comment by loserskater** [comment]
> 1. search option in app list

Done: 6e3413b237fff95329db7f006a2e224a13684769

> 1. reboot option

Done: 13dbad606ae61391eb8a3908287481fe29ea98ec

**Comment by ja-som** [comment]
Thanks ;)
